library(rvest)
library(tidyverse)
library(jsonlite)
library(stringr)
library(xml2)
library(plyr)
library(httr)
library(anytime)
url<-"https://s2.coinmarketcap.com/generated/search/quick_search.json"
url1<-"https://s2.coinmarketcap.com/generated/search/quick_search_exchanges.json"
coinlist<-fromJSON(url)
exchangelist<-fromJSON(url1)
write.csv(coinlist,"coinlist.csv",row.names=F)
write.csv(exchangelist,"exchangelist.csv",row.names=f)

for(i in 1:nrow(coinlist)){
  url3<-paste("https://graphs2.coinmarketcap.com/currencies/",coinlist[i,4],"/",sep="")
  data<-fromJSON(url3)
  mcap<-data$market_cap_by_available_supply%>%as.data.frame()
  pUSD<-data$price_usd%>%as.data.frame()
  pBTC<-data$price_btc%>%as.data.frame()
  vol<-data$volume_usd%>%as.data.frame()
  #pPLT<-data$price_platform%>%as.data.frame()
  names(mcap)<-c("Time","MarketCap")
  names(pUSD)<-c("Time","Price(USD)")
  #names(pPLT)<-c("Time","Price(plateform)")
  names(pBTC)<-c("Time","Price(BTC)")
  names(vol)<-c("Time","Volume")
  coindata<-merge(mcap,pUSD,by=c("Time"),all=TRUE)
  coindata1<-merge(vol,pBTC,by=c("Time"),all=TRUE)
  coindata1<-merge(coindata,coindata1,by=c("Time"),all=TRUE)
  #coindata1<-merge(coindata1,vol,by=c("Time"),all=TRUE)
  coindata1$Time<-anytime(coindata1$Time/1000)
  coindata1<-cbind(coindata1,Coin=coinlist[i,4])
  write.csv(coindata1,paste(coinlist[i,4],".csv",sep=""),row.names = F)
  print(i)
  }
